### ISSUE TITLE
another stderror

### ISSUE THREAD

**Issue by nobe0716** [yous/lime#2] opened 2016-01-07 07:23 UTC
![new_issue](https://cloud.githubusercontent.com/assets/5964919/12164697/ec86e01e-b55a-11e5-81d7-ad3ef42a7df8.png)

I faced error after pull newest version

**Comment by yous** [comment] 2016-01-07 07:32
What version of Zsh are you using?

**Comment by nobe0716** [comment] 2016-01-07 07:37
zsh 4.3.11 (x86_64-redhat-linux-gnu)

**Comment by yous** [comment] 2016-01-07 08:14
I pushed the fix. Please let me know if you still have the problem after an update.

**Closed as completed** 2016-01-07 08:13 UTC

**Comment by nobe0716** [comment] 2016-01-07 08:23
'git_compare_version:1 ~' has been disappeared, but still 'prompt_lime_git_dirty:1: unknown sort specifier ' remains

**Comment by yous** [comment] 2016-01-07 08:34
Oops, that problem is caused by the same issue. I pushed the fix. Please check again.
